version: '3'
services:
  cross-seed-proxy:
    image: thisisgm/cross-seed-proxy:latest
    container_name: cross-seed-proxy
    ports:
      - "5000:5000"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    restart: unless-stopped
    networks:
      - docker

networks:
  docker:
    external: true
